"""Deprecated product aliases for :mod:`hwcdq.profile`."""

from hwcdq.profile import (
    APP_DISPLAY_NAME,
    LEGACY_SETTINGS_APPLICATION_NAME,
    LEGACY_SETTINGS_ORGANIZATION_NAME,
    MODEL_MAX_CURRENT_A,
    MODEL_MAX_VOLTAGE_V,
    MODEL_MIN_CURRENT_A,
    MODEL_MIN_VOLTAGE_V,
)


__all__ = [
    "APP_DISPLAY_NAME",
    "LEGACY_SETTINGS_APPLICATION_NAME",
    "LEGACY_SETTINGS_ORGANIZATION_NAME",
    "MODEL_MAX_CURRENT_A",
    "MODEL_MAX_VOLTAGE_V",
    "MODEL_MIN_CURRENT_A",
    "MODEL_MIN_VOLTAGE_V",
]
