"""Qt-free public client library for the Pidzoom/HWCDQ HW178P charger."""

from __future__ import annotations

from .diagnostics import DiagnosticLogger
from .errors import (
    AmbiguousCommandResultError,
    AuthenticationError,
    BackendError,
    CommandRejectedError,
    CommandTimeoutError,
    FrameStreamError,
    GattTopologyError,
    InvalidStateError,
    SafetyInterlockError,
    TransportDisconnectedError,
    UnexpectedResponseError,
)
from .models import (
    AmbiguousOutcome,
    DeviceAdvertisement,
    EventKind,
    GattCharacteristic,
    GattService,
    SelectedGattTopology,
    SessionEvent,
    SessionSnapshot,
    SessionState,
)
from .profile import (
    AccessMode,
    ChargerProfile,
    Credential,
    DeviceTarget,
    EffectiveLimits,
    GattProfile,
    NumericRange,
    PIDZOOM_HW178P,
    SessionOptions,
)
from .protocol import (
    APK_FALLBACK_CREDENTIAL,
    ProtocolError,
    decode_packet,
    derive_password_credential,
    encode_check_password,
    encode_check_password_credential,
    encode_get_config,
    encode_get_firmware,
    encode_get_serial,
    encode_get_telemetry,
    encode_set_current,
    encode_set_voltage,
    encode_start,
    encode_stop,
    verify_checksum,
)
from .session import ChargerSession
from .transport import AsyncGattTransport, AsyncScanner


__version__ = "0.1.0"


__all__ = [
    "__version__",
    "APK_FALLBACK_CREDENTIAL",
    "ProtocolError",
    "decode_packet",
    "derive_password_credential",
    "encode_check_password",
    "encode_check_password_credential",
    "encode_get_config",
    "encode_get_firmware",
    "encode_get_serial",
    "encode_get_telemetry",
    "encode_set_current",
    "encode_set_voltage",
    "encode_start",
    "encode_stop",
    "verify_checksum",
    "DiagnosticLogger",
    "AccessMode",
    "ChargerProfile",
    "Credential",
    "DeviceTarget",
    "EffectiveLimits",
    "GattProfile",
    "NumericRange",
    "PIDZOOM_HW178P",
    "SessionOptions",
    "ChargerSession",
    "AmbiguousOutcome",
    "DeviceAdvertisement",
    "EventKind",
    "GattCharacteristic",
    "GattService",
    "SelectedGattTopology",
    "SessionEvent",
    "SessionSnapshot",
    "SessionState",
    "AsyncGattTransport",
    "AsyncScanner",
    "AmbiguousCommandResultError",
    "AuthenticationError",
    "BackendError",
    "CommandRejectedError",
    "CommandTimeoutError",
    "FrameStreamError",
    "GattTopologyError",
    "InvalidStateError",
    "SafetyInterlockError",
    "TransportDisconnectedError",
    "UnexpectedResponseError",
]
