"""Deprecated import shim for :mod:`hwcdq.protocol`."""

from hwcdq.protocol import (
    APK_FALLBACK_CREDENTIAL,
    AUTH_CREDENTIAL_LENGTH,
    OP_CHECK_PASSWORD,
    OP_GET_CONFIG,
    OP_GET_FIRMWARE,
    OP_GET_SERIAL,
    OP_GET_TELEMETRY,
    OP_OUTPUT_CONTROL,
    OP_SET_CURRENT,
    OP_SET_VOLTAGE,
    ProtocolError,
    decode_packet,
    derive_password_credential,
    encode_check_password,
    encode_check_password_credential,
    encode_get_config,
    encode_get_firmware,
    encode_get_serial,
    encode_get_telemetry,
    encode_packet,
    encode_set_current,
    encode_set_voltage,
    encode_start,
    encode_stop,
    verify_checksum,
)


__all__ = [
    "APK_FALLBACK_CREDENTIAL",
    "AUTH_CREDENTIAL_LENGTH",
    "OP_CHECK_PASSWORD",
    "OP_GET_CONFIG",
    "OP_GET_FIRMWARE",
    "OP_GET_SERIAL",
    "OP_GET_TELEMETRY",
    "OP_OUTPUT_CONTROL",
    "OP_SET_CURRENT",
    "OP_SET_VOLTAGE",
    "ProtocolError",
    "decode_packet",
    "derive_password_credential",
    "encode_check_password",
    "encode_check_password_credential",
    "encode_get_config",
    "encode_get_firmware",
    "encode_get_serial",
    "encode_get_telemetry",
    "encode_packet",
    "encode_set_current",
    "encode_set_voltage",
    "encode_start",
    "encode_stop",
    "verify_checksum",
]
